language: node_js
node_js:
  - 'stable'
<<<<<<< HEAD
  - '8'
  - '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - yarn lint
  - yarn test
  - yarn build --release
=======
  - '11.3.0'
script:
  - yarn lint
  - yarn test
>>>>>>> release
