export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const SET_CHECKOUT_STEPS = 'SET_CHECKOUT_STEPS';
export const NEXT_CHECKOUT_STEP = 'NEXT_CHECKOUT_STEP';
export const PREVIOUS_CHECKOUT_STEP = 'PREVIOUS_CHECKOUT_STEP';
export const GO_TO_CHECKOUT_STEP = 'GO_TO_CHECKOUT_STEP';

export const REQUEST_OFFER = 'REQUEST_OFFER';
export const RECEIVE_OFFER = 'RECEIVE_OFFER';

export const SET_CUSTOMER_TOKEN = 'SET_CUSTOMER_TOKEN';
export const LOGOUT = 'CUSTOMER_LOGOUT';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';

export const REQUEST_ACCESS = 'REQUEST_ACCESS';
export const GIVE_ACCESS = 'GIVE_ACCESS';
export const RECEIVE_ACCESS_ERROR = 'RECEIVE_ACCESS_ERROR';
export const RESET_ACCESS_ERROR = 'RESET_ACCESS_ERROR';

export const NEW_CROSS_COM_MESSAGE = 'NEW_CROSS_COM_MESSAGE';
