export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const SET_CHECKOUT_STEPS = 'SET_CHECKOUT_STEPS';
export const NEXT_CHECKOUT_STEP = 'NEXT_CHECKOUT_STEP';
export const PREVIOUS_CHECKOUT_STEP = 'PREVIOUS_CHECKOUT_STEP';
export const GO_TO_CHECKOUT_STEP = 'GO_TO_CHECKOUT_STEP';

export const REQUEST_OFFER = 'REQUEST_OFFER';
export const SET_OFFER = 'SET_OFFER';
export const SET_PRICE = 'SET_PRICE';
export const SET_TRIAL = 'SET_TRIAL';

export const SET_CUSTOMER_TOKEN = 'SET_CUSTOMER_TOKEN';
export const LOGOUT = 'LOGOUT';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_CONSENTS = 'SET_CONSENTS';
export const SET_TEMP_EMAIL = 'SET_TEMP_EMAIL';
export const SET_USER_EMAIL = 'SET_USER_EMAIL';

export const REQUEST_ACCESS = 'REQUEST_ACCESS';
export const GIVE_ACCESS = 'GIVE_ACCESS';
export const RECEIVE_ACCESS_ERROR = 'RECEIVE_ACCESS_ERROR';
export const RESET_ACCESS_ERROR = 'RESET_ACCESS_ERROR';

export const SET_REGISTERED_FLAG = 'SET_REGISTERED_FLAG';
